# Generated by Django 4.0.2 on 2022-11-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('cnic', models.CharField(max_length=13)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_cnic', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('election_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('candidate_id', models.IntegerField()),
                ('casted_at', models.DateTimeField(max_length=255)),
                ('status', models.CharField(choices=[('pn', 'Pending'), ('ac', 'Accepted'), ('rj', 'Rejected')], default='pn', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('election_title', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField(default=None)),
                ('end_at', models.DateTimeField(default=None)),
                ('candidates', models.ManyToManyField(to='elections.Candidate')),
            ],
        ),
    ]
